# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CurrentLocation
                                 A QGIS plugin
 plugin which contains a single click action
for creating a new shapefile
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-09
        copyright            : (C) 2018 by Collins Lenjo
        email                : collinslenjo.cl@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CurrentLocation class from file CurrentLocation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .current_location import CurrentLocation
    return CurrentLocation(iface)
